---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 742722654952673281-Jm50pYr7LWHARZSQn5TwgdNHjpAANkW
:access_token_secret: 7njNInYQ1RaD3U22bkTTwIRWjpB1t12ZoMwvLFbd1sDys
